### ISSUE TITLE
An uncleared step in TrajectoryAttention.forward()

### ISSUE THREAD

**Issue by ofir1080** [facebookresearch/Motionformer#5]
Hello, thanks for this great work and the shared code.
A small issue I have been trying to figure out:
in vit_helper.py.TrajectoryAttention.forward(), when the temporal attention is applied:
```

1.         x = rearrange(x, '(b h) s f d -> b s f (h d)', b=B)
2.         x_diag = rearrange(x, 'b (g n) f d -> b g n f d', g=F)
3.         x_diag = torch.diagonal(x_diag, dim1=-4, dim2=-2)
4.         x_diag = rearrange(x_diag, f'b n d f -> b (f n) d', f=F)
5.         q2 = self.proj_q(x_diag)
6.         k2, v2 = self.proj_kv(x).chunk(2, dim=-1)
7.         q2 = rearrange(q2, f'b s (h d) -> b h s d', h=h)
8.         x, k2, v2 = map(
9.             lambda t: rearrange(t, f'b s f (h d) -> b h s f d', f=F,  h=h), (x, k2, v2))
10.         q2 *= self.scale
11.         attn = torch.einsum('b h s d, b h s f d -> b h s f', q2, k2)
12.         attn = attn.softmax(dim=-1)
13.         x = torch.einsum('b h s f, b h s f d -> b h s d', attn, x)
14.         x = rearrange(x, f'b h s d -> b s (h d)')

```
in line 249 (here 13), why is EINSUM operation is applied on **attn** and _**x**?
in the paper, the temporal attention is applied as usual:
![image](https://user-images.githubusercontent.com/40369687/130232015-70a3311e-e430-4a04-a2d6-a21228586700.png)
 but in the code it seem like `v^{\sim}_{stt'}` is replaced with the reshaped version `x`.

In addition, I am confused since `x` is reshaped in line (here 8) together with `k1`, `v1`. So it might seem to be intentional.

Thanks!

**Comment by dylan-campbell** [comment]
Hi @ofir1080, thank you for picking that up! yes, the second x on line 13 is a typo - it should be v2. This has the effect of using an identity projection rather than a learned one (i.e. using v = x rather than v = Wx). I've submitted a pull request (#6) to correct this, while still keeping the original code to facilitate replication.

**Comment by ofir1080** [comment]
Sure, thanks again for sharing!
